// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBOdFLvWpEkb0nbe-kYvuS6xUaxBptuXg',
    appId: '1:56561590022:android:6c33bd929955a143c94887',
    messagingSenderId: '56561590022',
    projectId: 'flutter-chat-app-fdc4b',
    storageBucket: 'flutter-chat-app-fdc4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCGbIDlLxdGRCHgxVvI4ehb6ThX5ml1xk',
    appId: '1:56561590022:ios:653449e4520dd04cc94887',
    messagingSenderId: '56561590022',
    projectId: 'flutter-chat-app-fdc4b',
    storageBucket: 'flutter-chat-app-fdc4b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArELKATGlTOhittVHYafq2vyP8x6NIW7g',
    authDomain: 'flutter-chat-app-fdc4b.firebaseapp.com',
    projectId: 'flutter-chat-app-fdc4b',
    storageBucket: 'flutter-chat-app-fdc4b.appspot.com',
    messagingSenderId: '56561590022',
    appId: '1:56561590022:web:1b886abc40e6cba6c94887',
    measurementId: 'G-XYLH1CB8QY',
  );
}
